export type CostEstimateSource = "infracost" | "manual" | "mixed";

export interface CostThresholds {
  critical: number;
  high: number;
  medium: number;
}

export const DEFAULT_COST_THRESHOLDS: CostThresholds = {
  medium: 100,
  high: 500,
  critical: 2000,
};

export const DEFAULT_COST_CURRENCY = "USD";
export const COST_ESTIMATE_NOT_PROVIDED_NOTE = "Cost estimate not provided";
export const EXPECTED_INFRACOST_SOURCE_COPY =
  "Paste JSON generated by Infracost, not Terraform plan JSON.";

export interface ImportedCostResourceEntry {
  address: string | null;
  currency: string;
  id: string;
  monthlyCostAfter: number | null;
  monthlyCostBefore: number | null;
  monthlyDelta: number | null;
  name: string | null;
  projectName: string | null;
  source: "infracost";
}

export interface ParsedInfracostReport {
  currency: string;
  entries: ImportedCostResourceEntry[];
  totalMonthlyCostAfter: number | null;
  totalMonthlyCostBefore: number | null;
  totalMonthlyDelta: number | null;
  warnings: string[];
}

export interface ManualCostEntry {
  currency: string;
  id: string;
  monthlyDelta: number;
  note?: string | null;
  resourceAddress: string;
  resourceName?: string | null;
}

export type CostReportNoteMode = "custom" | "none" | "not-provided";

export interface CostImpactState {
  customNote: string;
  importedReport: ParsedInfracostReport | null;
  manualEntries: ManualCostEntry[];
  noteMode: CostReportNoteMode;
  thresholds: CostThresholds;
}

export interface ResourceCostEstimate {
  address: string | null;
  currency: string;
  monthlyCostAfter: number | null;
  monthlyCostBefore: number | null;
  monthlyDelta: number | null;
  name: string | null;
  source: CostEstimateSource;
}

export interface PlanCostEstimate {
  currency: string;
  hasMappedResources: boolean;
  importedEntryCount: number;
  manualEntryCount: number;
  mappedResourceCount: number;
  note: string | null;
  resourceEntries: ResourceCostEstimate[];
  source: CostEstimateSource;
  thresholds: CostThresholds;
  totalMonthlyCostAfter: number | null;
  totalMonthlyCostBefore: number | null;
  totalMonthlyDelta: number | null;
}

export const DEFAULT_COST_IMPACT_STATE: CostImpactState = {
  customNote: "",
  importedReport: null,
  manualEntries: [],
  noteMode: "none",
  thresholds: DEFAULT_COST_THRESHOLDS,
};

export type ParseInfracostReportResult =
  | {
      ok: true;
      report: ParsedInfracostReport;
    }
  | {
      expectedSourceCopy: string;
      message: string;
      ok: false;
    };

export function hasCostImpactState(state: CostImpactState): boolean {
  return (
    state.importedReport !== null ||
    state.manualEntries.length > 0 ||
    state.noteMode !== "none" ||
    state.customNote.trim().length > 0
  );
}
