export const summaryCards = [
  {
    title: "Creates",
    value: "--",
    description: "New resources that will be added after apply.",
    tone: "positive",
  },
  {
    title: "Updates",
    value: "--",
    description: "In-place changes across existing infrastructure.",
    tone: "default",
  },
  {
    title: "Deletes",
    value: "--",
    description: "Resources removed or destroyed from the plan.",
    tone: "critical",
  },
  {
    title: "Replacements",
    value: "--",
    description: "Destroy and recreate operations that expand blast radius.",
    tone: "warning",
  },
  {
    title: "High Risk",
    value: "--",
    description:
      "IAM, security, database, and network changes to inspect first.",
    tone: "critical",
  },
] as const;

export const workflowSteps = [
  {
    step: "Step 1",
    title: "Generate a plan JSON.",
    description:
      "Run Terraform locally and convert the saved plan to terraform show -json output.",
  },
  {
    step: "Step 2",
    title: "Paste or upload it.",
    description:
      "Bring the plan into the browser workspace with paste, drag-and-drop upload, or sample fixtures.",
  },
  {
    step: "Step 3",
    title: "Review risk and blast radius.",
    description:
      "Scan the change summary, inspect high-risk resources, and focus on destructive operations first.",
  },
] as const;

export const useCases = [
  "PR review for infrastructure changes.",
  "Catch destructive changes before apply.",
  "Review IAM, security group, database, and network changes.",
  "Create a Markdown summary for code review.",
] as const;

export const faqItems = [
  {
    question: "What input does this Terraform plan visualizer accept?",
    answer:
      "The analyzer accepts JSON generated by terraform show -json from a saved plan file such as tfplan. Paste the JSON, upload a plan.json file, or load a sample fixture. Raw HCL, state files, and binary tfplan files need to be converted first.",
  },
  {
    question: "Does my Terraform plan get uploaded?",
    answer:
      "No. Terraform plan analysis runs in this browser tab, share-safe links only store reviewer state, and exports are redacted by default. Optional local history can save a redacted copy of the plan on this device so you can reopen it later—nothing is sent to a server.",
  },
  {
    question: "How do I generate Terraform plan JSON?",
    answer:
      "Run terraform plan -out=tfplan, then convert it with terraform show -json tfplan > plan.json. If you use Terraform workspaces, select the correct workspace before creating the plan file.",
  },
  {
    question: "Can this detect destructive Terraform changes?",
    answer:
      "Yes. The analyzer highlights deletes, replacements, dependency blast radius, high-risk IAM and network changes, and optional cost spikes when you import cost data. It helps reviewers prioritize destructive changes before terraform apply, but it is still a review aid rather than a policy engine.",
  },
  {
    question: "Why are some dependencies missing from the graph?",
    answer:
      "The dependency graph is reconstructed from the references and edges Terraform exposes in plan JSON. Implicit runtime relationships, provider-internal behavior, and values that stay unknown until apply may not appear as graph edges.",
  },
] as const;

export { productTools as relatedTools } from "@/lib/shared/tools-registry";

export const analyzerChecks = [
  "Normalizes Terraform resource changes into creates, updates, deletes, and replacements so reviewers can sort by impact instead of scanning raw JSON.",
  "Highlights risky deletes, replacements, IAM changes, security boundary updates, database churn, and provider or module hotspots that deserve a closer read.",
  "Builds a best-effort dependency graph and blast-radius view from the plan so you can focus on affected upstream and downstream resources first.",
  "Supports optional imported cost data and redacted exports, while share-safe links keep only the current reviewer state in the URL.",
] as const;

export const terraformActionExplanations = [
  {
    action: "Create",
    description:
      "A new resource appears after apply. Review naming, tags, scope, and whether the resource should exist in this workspace at all.",
  },
  {
    action: "Update",
    description:
      "Terraform will modify a resource in place. Watch for policy broadening, ingress expansion, retention changes, or configuration drift hidden inside large diffs.",
  },
  {
    action: "Delete",
    description:
      "The resource is destroyed. Deletes are usually the first changes to triage because they can remove traffic paths, storage, or access unexpectedly.",
  },
  {
    action: "Replace",
    description:
      "Terraform will destroy and recreate the resource. Replacements often carry the highest operational risk because they combine downtime, recreation, and dependency churn.",
  },
  {
    action: "No-op or unknown",
    description:
      "Some values stay unknown until apply, and unchanged resources may still matter if downstream edges or outputs reference them.",
  },
] as const;

export const riskyTerraformChanges = [
  "Security group ingress widened from trusted CIDRs to 0.0.0.0/0 or ::/0.",
  "Database, cache, or queue replacements that can trigger downtime, failover, or data migration work.",
  "IAM policy updates that broaden principals, actions, or wildcard resource access.",
  "DNS record deletes or replacements that can break cutovers, health checks, or public entry points.",
  "Large multi-module plans where a single provider or shared module fans out across dozens of resources.",
] as const;

export const reviewerWorkflowSteps = [
  "Generate terraform show -json output locally, then load it into the browser workspace. The analyzer does not require a login or backend upload.",
  "Review deletes, replacements, and high-risk findings first. If the graph feels sparse, treat it as a plan-derived guide rather than a complete runtime dependency map.",
  "Turn on redaction before copying a PR comment or downloading Markdown, HTML, or JSON reports. Share-safe links keep your current filters and tabs, not the plan itself.",
  "Paste the exported Markdown into the pull request so reviewers can discuss blast radius, risky resources, and follow-up checks without sharing raw plan JSON.",
] as const;

export const analyzerLimitations = [
  "The tool expects terraform show -json output. It does not analyze raw binary tfplan files directly.",
  "Unknown values remain unknown until apply, so some final identifiers, IPs, or computed attributes are intentionally incomplete.",
  "Dependency graphs are best effort and only reflect relationships exposed by the plan JSON and normalized references.",
  "Redaction protects reports by default, but aggressive redaction can also hide context that a reviewer may need to interpret a change.",
  "Optional manual cost entries are reviewer estimates, not provider-billed truth.",
] as const;

export const practicalExamples = [
  {
    title: "AWS security group ingress change",
    summary:
      "A previously internal application load balancer security group starts allowing HTTPS from 0.0.0.0/0.",
    reviewerFocus:
      "Check whether the change is intentional, whether a WAF or ingress tier is expected to absorb public traffic, and whether the blast radius reaches shared modules or target groups.",
  },
  {
    title: "Database replacement",
    summary:
      "An aws_db_instance switches engine family or storage settings and Terraform marks it for replacement.",
    reviewerFocus:
      "Inspect downtime expectations, snapshot strategy, cutover sequencing, and any downstream consumers that rely on endpoint stability.",
  },
  {
    title: "IAM policy update",
    summary:
      "A policy diff adds broader actions or resources, such as wildcard access to S3 buckets or KMS keys.",
    reviewerFocus:
      "Review least-privilege intent, principal scope, and whether the policy update should be split from unrelated infra changes for easier approval.",
  },
  {
    title: "DNS record deletion",
    summary:
      "A Route53 or Cloud DNS record is deleted during an environment cleanup or load balancer migration.",
    reviewerFocus:
      "Confirm TTL strategy, traffic cutover timing, and whether health checks, certificates, or downstream aliases still depend on the record.",
  },
  {
    title: "Large multi-module plan",
    summary:
      "A plan touches networking, data, and compute modules at once, producing a long list of changes that are hard to triage manually.",
    reviewerFocus:
      "Use provider and module summaries, blast-radius focus, and filtered findings to narrow review onto the highest-risk clusters before reading the full diff.",
  },
] as const;
