"use client";

import { useMemo, useState } from "react";
import type { NormalizedPlan } from "@/features/terraform-plan/domain/normalizedPlanTypes";
import {
  DEFAULT_COST_CURRENCY,
  EXPECTED_INFRACOST_SOURCE_COPY,
  type CostImpactState,
  type CostReportNoteMode,
  type ManualCostEntry,
} from "@/features/terraform-plan/cost/costTypes";
import {
  formatCurrencyAmount,
  formatMonthlyDelta,
} from "@/features/terraform-plan/cost/costUtils";
import { parseInfracostReportJson } from "@/features/terraform-plan/cost/parseInfracostReport";
import { cn } from "@/lib/utils";

interface CostImpactPanelProps {
  normalizedPlan: NormalizedPlan | null;
  onChange: (value: CostImpactState) => void;
  value: CostImpactState;
}

type NoticeTone = "critical" | "default" | "positive";

const noticeToneClasses = {
  critical: "border-critical bg-critical-soft text-critical",
  default: "border-border bg-surface-muted text-foreground",
  positive: "border-positive bg-positive-soft text-positive",
} as const;

function createManualEntryId(): string {
  return typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function formatSourceName(entry: ManualCostEntry): string {
  return entry.resourceName?.trim() || entry.resourceAddress;
}

export function CostImpactPanel({
  normalizedPlan,
  onChange,
  value,
}: CostImpactPanelProps) {
  const [importText, setImportText] = useState("");
  const [importNotice, setImportNotice] = useState<{
    message: string;
    tone: NoticeTone;
  }>({
    message: EXPECTED_INFRACOST_SOURCE_COPY,
    tone: "default",
  });
  const [manualAddress, setManualAddress] = useState("");
  const [manualDelta, setManualDelta] = useState("");
  const [manualCurrency, setManualCurrency] = useState(DEFAULT_COST_CURRENCY);
  const resourceAddressOptions = useMemo(
    () =>
      normalizedPlan?.resourceChanges.map((resourceChange) => resourceChange.address) ??
      [],
    [normalizedPlan],
  );

  const handleImport = (text: string) => {
    const result = parseInfracostReportJson(text);

    if (!result.ok) {
      setImportNotice({
        message: `${result.message} ${result.expectedSourceCopy}`,
        tone: "critical",
      });
      return;
    }

    onChange({
      ...value,
      importedReport: result.report,
    });
    setImportNotice({
      message: `Imported ${result.report.entries.length} cost entries. Total delta ${formatMonthlyDelta(
        result.report.totalMonthlyDelta,
        result.report.currency,
      )}.`,
      tone: "positive",
    });
  };

  return (
    <section className="border-border bg-background rounded-lg border p-4 sm:p-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <h3 className="text-foreground text-lg font-semibold">Cost impact</h3>
          <p className="text-muted-foreground mt-1 max-w-3xl text-sm leading-7">
            Optional and local-only. Paste or upload existing Infracost JSON, or
            add rough manual monthly deltas without calling external APIs.
          </p>
        </div>

        <div className="border-border bg-surface rounded-lg border px-3 py-2 text-sm text-muted-foreground">
          Works without cost data
        </div>
      </div>

      <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]">
        <section className="border-border bg-surface rounded-lg border p-4">
          <h4 className="text-foreground text-sm font-semibold">
            Import existing Infracost JSON
          </h4>
          <p className="text-muted-foreground mt-1 text-sm leading-6">
            Paste JSON generated by Infracost, or upload a saved `.json` file.
          </p>

          <textarea
            aria-label="Paste Infracost JSON"
            className="border-border bg-background text-foreground mt-3 min-h-40 w-full rounded-lg border px-3 py-3 text-sm leading-6"
            onChange={(event) => setImportText(event.target.value)}
            placeholder='{"currency":"USD","projects":[...]}'
            spellCheck={false}
            value={importText}
          />

          <div className="mt-3 flex flex-wrap gap-3">
            <label className="border-border bg-background text-foreground hover:bg-surface-muted inline-flex cursor-pointer rounded-lg border px-3 py-2 text-sm font-medium transition-colors">
              Upload JSON
              <input
                accept=".json,application/json"
                className="sr-only"
                onChange={(event) => {
                  const file = event.target.files?.[0];

                  if (!file) {
                    return;
                  }

                  const reader = new FileReader();

                  reader.onload = () => {
                    const nextText =
                      typeof reader.result === "string" ? reader.result : "";

                    setImportText(nextText);
                    handleImport(nextText);
                  };
                  reader.onerror = () => {
                    setImportNotice({
                      message: "We could not read that file locally.",
                      tone: "critical",
                    });
                  };
                  reader.readAsText(file);
                  event.currentTarget.value = "";
                }}
                type="file"
              />
            </label>
            <button
              type="button"
              className="bg-brand text-brand-foreground hover:bg-brand/90 inline-flex rounded-lg px-3 py-2 text-sm font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-55"
              disabled={importText.trim().length === 0}
              onClick={() => handleImport(importText)}
            >
              Import cost JSON
            </button>
            <button
              type="button"
              className="border-border bg-background text-foreground hover:bg-surface-muted inline-flex rounded-lg border px-3 py-2 text-sm font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-55"
              disabled={value.importedReport === null}
              onClick={() => {
                onChange({
                  ...value,
                  importedReport: null,
                });
                setImportNotice({
                  message: EXPECTED_INFRACOST_SOURCE_COPY,
                  tone: "default",
                });
              }}
            >
              Clear imported report
            </button>
          </div>

          <div
            className={cn(
              "mt-3 rounded-lg border px-4 py-3 text-sm leading-6",
              noticeToneClasses[importNotice.tone],
            )}
          >
            {importNotice.message}
          </div>

          {value.importedReport ? (
            <div className="mt-4 flex flex-wrap gap-2">
              <span className="border-border bg-background text-muted-foreground inline-flex rounded-full border px-2.5 py-1 text-xs font-medium">
                {value.importedReport.entries.length} imported entries
              </span>
              <span className="border-border bg-background text-muted-foreground inline-flex rounded-full border px-2.5 py-1 text-xs font-medium">
                Delta {formatMonthlyDelta(
                  value.importedReport.totalMonthlyDelta,
                  value.importedReport.currency,
                )}
              </span>
              <span className="border-border bg-background text-muted-foreground inline-flex rounded-full border px-2.5 py-1 text-xs font-medium">
                Before {formatCurrencyAmount(
                  value.importedReport.totalMonthlyCostBefore,
                  value.importedReport.currency,
                )}
              </span>
              <span className="border-border bg-background text-muted-foreground inline-flex rounded-full border px-2.5 py-1 text-xs font-medium">
                After {formatCurrencyAmount(
                  value.importedReport.totalMonthlyCostAfter,
                  value.importedReport.currency,
                )}
              </span>
            </div>
          ) : null}
        </section>

        <div className="space-y-4">
          <section className="border-border bg-surface rounded-lg border p-4">
            <h4 className="text-foreground text-sm font-semibold">
              Manual estimates
            </h4>
            <p className="text-muted-foreground mt-1 text-sm leading-6">
              Add rough monthly deltas per resource when you do not have imported
              cost data for that change.
            </p>

            <div className="mt-3 grid gap-3">
              <input
                aria-label="Manual cost resource address"
                className="border-border bg-background text-foreground rounded-lg border px-3 py-2 text-sm"
                list="terraform-plan-cost-addresses"
                onChange={(event) => setManualAddress(event.target.value)}
                placeholder="module.app.aws_instance.api"
                value={manualAddress}
              />
              <datalist id="terraform-plan-cost-addresses">
                {resourceAddressOptions.map((address) => (
                  <option key={address} value={address} />
                ))}
              </datalist>
              <div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_7rem]">
                <input
                  aria-label="Manual monthly delta"
                  className="border-border bg-background text-foreground rounded-lg border px-3 py-2 text-sm"
                  inputMode="decimal"
                  onChange={(event) => setManualDelta(event.target.value)}
                  placeholder="125.00"
                  value={manualDelta}
                />
                <input
                  aria-label="Manual cost currency"
                  className="border-border bg-background text-foreground rounded-lg border px-3 py-2 text-sm uppercase"
                  maxLength={8}
                  onChange={(event) =>
                    setManualCurrency(event.target.value.toUpperCase())
                  }
                  value={manualCurrency}
                />
              </div>
              <button
                type="button"
                className="bg-brand text-brand-foreground hover:bg-brand/90 inline-flex rounded-lg px-3 py-2 text-sm font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-55"
                disabled={
                  manualAddress.trim().length === 0 ||
                  Number.isNaN(Number.parseFloat(manualDelta))
                }
                onClick={() => {
                  onChange({
                    ...value,
                    manualEntries: [
                      ...value.manualEntries,
                      {
                        currency: manualCurrency.trim() || DEFAULT_COST_CURRENCY,
                        id: createManualEntryId(),
                        monthlyDelta: Number.parseFloat(manualDelta),
                        resourceAddress: manualAddress.trim(),
                        resourceName: manualAddress.trim(),
                      },
                    ],
                  });
                  setManualAddress("");
                  setManualDelta("");
                  setManualCurrency(DEFAULT_COST_CURRENCY);
                }}
              >
                Add manual estimate
              </button>
            </div>

            <div className="mt-4 space-y-2">
              {value.manualEntries.length === 0 ? (
                <p className="text-muted-foreground text-sm leading-6">
                  No manual estimates added yet.
                </p>
              ) : (
                value.manualEntries.map((entry) => (
                  <article
                    key={entry.id}
                    className="border-border bg-background flex items-start justify-between gap-3 rounded-lg border p-3"
                  >
                    <div>
                      <p className="text-foreground text-sm font-medium">
                        {formatSourceName(entry)}
                      </p>
                      <p className="text-muted-foreground mt-1 text-sm leading-6">
                        {formatMonthlyDelta(entry.monthlyDelta, entry.currency)}
                      </p>
                    </div>
                    <button
                      type="button"
                      className="border-border bg-background text-foreground hover:bg-surface-muted inline-flex rounded-lg border px-3 py-2 text-sm font-medium transition-colors"
                      onClick={() =>
                        onChange({
                          ...value,
                          manualEntries: value.manualEntries.filter(
                            (manualEntry) => manualEntry.id !== entry.id,
                          ),
                        })
                      }
                    >
                      Remove
                    </button>
                  </article>
                ))
              )}
            </div>
          </section>

          <section className="border-border bg-surface rounded-lg border p-4">
            <h4 className="text-foreground text-sm font-semibold">
              Reviewer note and thresholds
            </h4>
            <p className="text-muted-foreground mt-1 text-sm leading-6">
              Thresholds control the optional cost findings. Notes are included
              in exports only when provided.
            </p>

            <div className="mt-3 grid gap-3">
              <select
                aria-label="Cost note"
                className="border-border bg-background text-foreground rounded-lg border px-3 py-2 text-sm"
                onChange={(event) =>
                  onChange({
                    ...value,
                    noteMode: event.target.value as CostReportNoteMode,
                  })
                }
                value={value.noteMode}
              >
                <option value="none">No reviewer note</option>
                <option value="not-provided">Cost estimate not provided</option>
                <option value="custom">Custom reviewer note</option>
              </select>

              {value.noteMode === "custom" ? (
                <textarea
                  aria-label="Custom cost note"
                  className="border-border bg-background text-foreground min-h-24 rounded-lg border px-3 py-3 text-sm leading-6"
                  onChange={(event) =>
                    onChange({
                      ...value,
                      customNote: event.target.value,
                    })
                  }
                  placeholder="Manual estimate provided for the highest-risk resources only."
                  value={value.customNote}
                />
              ) : null}

              <div className="grid gap-3 sm:grid-cols-3">
                <label className="text-muted-foreground text-sm">
                  Medium &gt;
                  <input
                    aria-label="Medium cost threshold"
                    className="border-border bg-background text-foreground mt-1 w-full rounded-lg border px-3 py-2 text-sm"
                    inputMode="decimal"
                    onChange={(event) => {
                      const nextValue = Number.parseFloat(event.target.value);

                      onChange({
                        ...value,
                        thresholds: {
                          ...value.thresholds,
                          medium: Number.isFinite(nextValue)
                            ? nextValue
                            : value.thresholds.medium,
                        },
                      });
                    }}
                    value={value.thresholds.medium}
                  />
                </label>
                <label className="text-muted-foreground text-sm">
                  High &gt;
                  <input
                    aria-label="High cost threshold"
                    className="border-border bg-background text-foreground mt-1 w-full rounded-lg border px-3 py-2 text-sm"
                    inputMode="decimal"
                    onChange={(event) => {
                      const nextValue = Number.parseFloat(event.target.value);

                      onChange({
                        ...value,
                        thresholds: {
                          ...value.thresholds,
                          high: Number.isFinite(nextValue)
                            ? nextValue
                            : value.thresholds.high,
                        },
                      });
                    }}
                    value={value.thresholds.high}
                  />
                </label>
                <label className="text-muted-foreground text-sm">
                  Critical &gt;
                  <input
                    aria-label="Critical cost threshold"
                    className="border-border bg-background text-foreground mt-1 w-full rounded-lg border px-3 py-2 text-sm"
                    inputMode="decimal"
                    onChange={(event) => {
                      const nextValue = Number.parseFloat(event.target.value);

                      onChange({
                        ...value,
                        thresholds: {
                          ...value.thresholds,
                          critical: Number.isFinite(nextValue)
                            ? nextValue
                            : value.thresholds.critical,
                        },
                      });
                    }}
                    value={value.thresholds.critical}
                  />
                </label>
              </div>
            </div>
          </section>
        </div>
      </div>
    </section>
  );
}
